### ISSUE TITLE
Resolving com.github.njeuk#dbmapper_2.11;2.3.19

### ISSUE THREAD

**Issue by cocodrino** [njeuk/dbmapper#1]
Hi, I've had some problems trying to use dbmapper..I'm using 

$ sbt --version
sbt launcher version 0.13.6

when I add the dependency, seems than sbt can't find this

``` sbt
[info] Resolving com.github.njeuk#dbmapper_2.11;2.3.19 ...
[warn]  module not found: com.github.njeuk#dbmapper_2.11;2.3.19
[warn] ==== local: tried
[warn]   /home/yo/.ivy2/local/com.github.njeuk/dbmapper_2.11/2.3.19/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   file:/home/yo/.activator/repository/com.github.njeuk/dbmapper_2.11/2.3.19/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   file:/home/yo/Downloads/proj/scalaPROJ/activator-1.3.2/repository/com.github.njeuk/dbmapper_2.11/2.3.19/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/github/njeuk/dbmapper_2.11/2.3.19/dbmapper_2.11-2.3.19.pom
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/github/njeuk/dbmapper_2.11/2.3.19/dbmapper_2.11-2.3.19.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.github.njeuk/dbmapper_2.11/2.3.19/ivys/ivy.xml
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.github.njeuk#dbmapper_2.11;2.3.19: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.github.njeuk:dbmapper_2.11:2.3.19 (/home/yo/Downloads/proj/scalaPROJ/shitdbshit/build.sbt#L7-8)
[warn]        +- shitdb:shitdb_2.11:1.0
sbt.ResolveException: unresolved dependency: com.github.njeuk#dbmapper_2.11;2.3.19: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:243)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:158)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:156)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:147)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:124)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$3.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:119)
    at sbt.IvySbt.withIvy(Ivy.scala:116)
    at sbt.IvySbt$Module.withModule(Ivy.scala:147)
    at sbt.IvyActions$.updateEither(IvyActions.scala:156)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1282)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1279)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1309)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$84.apply(Defaults.scala:1307)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1312)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1306)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1324)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1264)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1242)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.njeuk#dbmapper_2.11;2.3.19: not found
[error] Total time: 2 s, completed Jun 28, 2015 5:54:48 PM
```

I try add bintray-sbt to my plugins but this gives me an error too, sinceraly I don't know what is bintray-sbt 

then I try add the project to my sbt using github

my build.scala

``` scala
import sbt._

object MyBuild extends Build {

   lazy val root = Project("root", file(".")) dependsOn(dbmappe)
   lazy valdbmappe =
      RootProject(uri("git://github.com/njeuk/dbmapper.git"))

}

```

seems works ok, except than the project files are different to the imports in the doc..is the doc updated?

from 
https://njeuk.github.io/dbmapper/latest/api/#com.github.njeuk.dbmapper.DbAsync$

``` scala
import com.github.njeuk.dbmapper.Implicits._ doesnt exist
```

from 
https://github.com/njeuk/dbmapper/blob/master/src/test/scala/com/github/njeuk/dbmapper/examples/Queries.scala 

``` scala
import com.github.njeuk.dbmapper.{DbAsyncConfig, DbAsync}
import com.github.njeuk.dbmapper.SqlInterpolation._
import com.github.njeuk.dbmapper.RowDataExtension.RowDataExtensionImplicit
```

doesnt exist neither
I'm not a sbt expert, actually my sbt knowledge is very poor, but I'd like a bit more simple way for install this lib or if you can provide me a right instructions I'd appreciate it...thanks

**Comment by njeuk** [comment]
Hi,

The artifacts are hosted at the JCentre Bintray Repository (https://bintray.com/njeuk/maven/dbmapper). 
Typically, most artifacts from Scala / Java open source projects get hosted at Maven Central, it is just pretty painful to setup a new account on there.
So for dbmapper we are hosting on bintray, which is a bit more modern and much less painful.

Recent SBT versions know how to find artifacts at Bintray, but you need to add the following setting to your build.sbt:
`resolvers += Resolver.jcenterRepo`

I have updated the README with the details, and also bumped the version number in the README to the latest versions.  So a minimal build.sbt would look like this (I just checked this on SBT 0.13.6):

```
root@1167a18c2bac:/minimal# cat build.sbt
name := """minimal"""

version := "1.0"

scalaVersion := "2.11.6"

resolvers += Resolver.jcenterRepo

libraryDependencies += "com.github.njeuk" %% "dbmapper" % "2.3.19"
```
